from typing import List
from BoardSpace import (BoardSpace, ShortcutSpace, Shortcut, TreatSpace)
from Card import (Color, Treat)

class Board:
    def __init__(self) -> None:
        self.board = self.generate_board()

    def generate_board(self):
        board = []
        board.append(BoardSpace(Color.RED))
        board.append(BoardSpace(Color.PURPLE))
        board.append(BoardSpace(Color.YELLOW))
        board.append(ShortcutSpace(Color.BLUE, Shortcut.PEPPERMINT_PASS))
        board.append(BoardSpace(Color.ORANGE))
        board.append(BoardSpace(Color.GREEN))
        board.append(BoardSpace(Color.RED))
        board.append(BoardSpace(Color.PURPLE))
        board.append(BoardSpace(Color.YELLOW))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.ORANGE))
        board.append(BoardSpace(Color.GREEN))
        board.append(BoardSpace(Color.RED))
        board.append(BoardSpace(Color.PURPLE))
        board.append(BoardSpace(Color.YELLOW))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.ORANGE))
        board.append(ShortcutSpace(Color.GREEN, Shortcut.GUMMY_PASS))
        board.append(BoardSpace(Color.RED))
        board.append(BoardSpace(Color.PURPLE))
        board.append(TreatSpace(Treat.PEPPERMINT))
        board.append(BoardSpace(Color.YELLOW))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.ORANGE))
        board.append(BoardSpace(Color.GREEN))
        board.append(BoardSpace(Color.RED))
        board.append(BoardSpace(Color.PURPLE, has_x=True))
        board.append(BoardSpace(Color.YELLOW))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.ORANGE))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.GREEN))
        board.append(BoardSpace(Color.RED))
        board.append(TreatSpace(Treat.GUM_DROP))
        board.append(BoardSpace(Color.PURPLE))
        board.append(BoardSpace(Color.YELLOW))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.ORANGE))
        board.append(BoardSpace(Color.GREEN))
        board.append(BoardSpace(Color.RED))
        board.append(BoardSpace(Color.PURPLE))
        board.append(BoardSpace(Color.YELLOW))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.ORANGE))
        board.append(TreatSpace(Treat.CHOCOLATE))
        board.append(BoardSpace(Color.RED))
        board.append(BoardSpace(Color.PURPLE))
        board.append(BoardSpace(Color.YELLOW))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.ORANGE))
        board.append(BoardSpace(Color.GREEN))
        board.append(BoardSpace(Color.RED))
        board.append(TreatSpace(Treat.LOLLI_POP))
        board.append(BoardSpace(Color.PURPLE))
        board.append(BoardSpace(Color.YELLOW, has_x=True))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.ORANGE))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.GREEN))
        board.append(BoardSpace(Color.RED))
        board.append(BoardSpace(Color.PURPLE))
        board.append(BoardSpace(Color.YELLOW))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.ORANGE))
        board.append(BoardSpace(Color.GREEN))
        board.append(BoardSpace(Color.RED))
        board.append(BoardSpace(Color.PURPLE))
        board.append(BoardSpace(Color.YELLOW))
        board.append(TreatSpace(Treat.ICE_CREAM))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.ORANGE))
        board.append(BoardSpace(Color.GREEN))
        board.append(BoardSpace(Color.RED))
        board.append(BoardSpace(Color.PURPLE))
        board.append(BoardSpace(Color.YELLOW))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.ORANGE))
        board.append(BoardSpace(Color.GREEN))
        board.append(BoardSpace(Color.RED))
        board.append(BoardSpace(Color.PURPLE))
        board.append(BoardSpace(Color.YELLOW))
        board.append(BoardSpace(Color.BLUE))
        board.append(BoardSpace(Color.ORANGE))
        board.append(BoardSpace(Color.GREEN))
        board.append(BoardSpace(Color.BLUE))
        for board_space in board:
            print(board_space.color)